#### Conways Game of Life


In [19]:
import numpy as np


def main():
    
    print("Implementation of Conway's Game of Life \n")
    print("Input Selection for Initial Automaton \n")
    print("Enter: 1 - Blinker, 2 - Glider, 3 - Gosper's Glider Gun, 4 - r-pentamino, 5 - Pattern(Class 3)")

    choice = int(input())
    if (choice ==1 ):
        print("Starting Blinker\n")
    elif (choice ==2 ):
        print("Starting Glider\n")
    elif (choice ==3 ):
        print("Starting Gosper's Glider Gun")
    elif (choice ==4 ):
        print("Starting r-pentamino")
    else :
        print("Starting Pattern(Class 3)")
    
    
    # Initialize empty matrix as 0

    #matrix = np.zeros( (101, 82) )
    matrix = np.zeros( (10, 10) )

    #blinker
    matrix[2,1]=1
    matrix[2,2]=1
    matrix[2,3]=1

    print(matrix)
    
    update_step(matrix)


def update_step(matrix):
    
    print(matrix.shape)
    
    rows,cols = matrix.shape
    
    for row_index in range(rows):
        for col_index in range(cols):
            print(matrix[row_index, col_index])
        print("\n")
    return matrix
    
if __name__=="__main__":
    main()


Implementation of Conway's Game of Life 

Input Selection for Initial Automaton 

Enter: 1 - Blinker, 2 - Glider, 3 - Gosper's Glider Gun, 4 - r-pentamino, 5 - Pattern(Class 3)
3
Starting Gosper's Glider Gun
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(10, 10)
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


0.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0


0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


